on: [push, pull_request]

name: ubuntu-latest

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
            sudo apt-get update && \
            sudo apt-get install --assume-yes --no-install-recommends \
                cmake libsdl2-dev libcapstone-dev

      - name: Configure
        uses: threeal/cmake-action@v1.2.0
        with:
            generator: Ninja

      - name: Build
        run: cmake --build build

      - name: Test
        run: |
            (cd build/test/cpu/alu && ./alu_tests)
            (cd build/test/bus && ./bus_tests)
            (cd build/test/hw && ./hw_tests)
